[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
tracing = { workspace = true }
testcontainers = { workspace = true }
tokio = {workspace = true}