[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {workspace = true}
derive_builder = { workspace = true}
strum = {workspace = true}
apache-avro = {workspace = true}
